name: 'AWS SSM Port Forwarding Session'
description: 'Start an SSM Port Forwarding Session in a github workflow'
inputs:
  target-id:
    description: 'Start session on instance'
    required: true
  portNumber:
    description: 'port number to forward to'
    required: true
    default: '8888'
  localPortNumber:
    description: 'local port number'
    required: true
    default: '8888'
outputs:
  session-id:
    description: 'ssm session id'
runs:
  using: 'node16'
  main: 'index.js'
  post: 'cleanup.js'